version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - "./client:/usr/src/app"
    command: npm start
    depends_on:
      - server
  server:
    build: ./server
    environment:
      - NODE_ENV=development
    env_file:
      - "./.env"
    volumes:
      - "./server:/usr/src/app"
    command: node server.js
